"""empty message

Revision ID: 27245bb30f4e
Revises: 9c66b12cabe1
Create Date: 2026-06-10 18:28:33.176615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27245bb30f4e'
down_revision = '9c66b12cabe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=False))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('is_banned')

    # ### end Alembic commands ###
