"""add attachment to posts

Revision ID: 9c66b12cabe1
Revises: c432d11cc381
Create Date: 2026-06-07 16:46:04.499504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c66b12cabe1'
down_revision = 'c432d11cc381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('attachment')

    # ### end Alembic commands ###
